### ISSUE TITLE
pkg_resources.DistributionNotFound: The 'pdb4amber==1.4' distribution was not found and is required by the application

### ISSUE THREAD

**Issue by hainm** [Amber-MD/cmake-buildscripts#52] opened 2017-09-25 04:54 UTC
Hi,

please see the log here (click "Raw log" and search for "pdb4amber -h")

https://travis-ci.org/Amber-MD/ambertools-ci/jobs/279367478

**Comment by multiplemonomials** [comment] 2017-09-25 05:01
@hainm Do you have any idea what that error means?  I sure don't.  `pdb4amber` works on my system, and it's definitely getting installed.  Is this some sort of PYTHONPATH-related error?

**Comment by multiplemonomials** [comment] 2017-09-25 05:01
Here's the installation log from the CI build:
```
running build
running build_py
creating /home/travis/TMP/build/AmberTools/src/pdb4amber/CMakeFiles/python-build
creating /home/travis/TMP/build/AmberTools/src/pdb4amber/CMakeFiles/python-build/lib
creating /home/travis/TMP/build/AmberTools/src/pdb4amber/CMakeFiles/python-build/lib/pdb4amber
copying pdb4amber/template.py -> /home/travis/TMP/build/AmberTools/src/pdb4amber/CMakeFiles/python-build/lib/pdb4amber
copying pdb4amber/utils.py -> /home/travis/TMP/build/AmberTools/src/pdb4amber/CMakeFiles/python-build/lib/pdb4amber
copying pdb4amber/amber_builder.py -> /home/travis/TMP/build/AmberTools/src/pdb4amber/CMakeFiles/python-build/lib/pdb4amber
copying pdb4amber/leap_runner.py -> /home/travis/TMP/build/AmberTools/src/pdb4amber/CMakeFiles/python-build/lib/pdb4amber
copying pdb4amber/residue.py -> /home/travis/TMP/build/AmberTools/src/pdb4amber/CMakeFiles/python-build/lib/pdb4amber
copying pdb4amber/pdb4amber.py -> /home/travis/TMP/build/AmberTools/src/pdb4amber/CMakeFiles/python-build/lib/pdb4amber
copying pdb4amber/compat.py -> /home/travis/TMP/build/AmberTools/src/pdb4amber/CMakeFiles/python-build/lib/pdb4amber
copying pdb4amber/leapify.py -> /home/travis/TMP/build/AmberTools/src/pdb4amber/CMakeFiles/python-build/lib/pdb4amber
copying pdb4amber/visualizer.py -> /home/travis/TMP/build/AmberTools/src/pdb4amber/CMakeFiles/python-build/lib/pdb4amber
copying pdb4amber/__init__.py -> /home/travis/TMP/build/AmberTools/src/pdb4amber/CMakeFiles/python-build/lib/pdb4amber
creating /home/travis/TMP/build/AmberTools/src/pdb4amber/CMakeFiles/python-build/lib/pdb4amber/builder
copying pdb4amber/builder/pytraj_build.py -> /home/travis/TMP/build/AmberTools/src/pdb4amber/CMakeFiles/python-build/lib/pdb4amber/builder
copying pdb4amber/builder/nab.py -> /home/travis/TMP/build/AmberTools/src/pdb4amber/CMakeFiles/python-build/lib/pdb4amber/builder
copying pdb4amber/builder/builder.py -> /home/travis/TMP/build/AmberTools/src/pdb4amber/CMakeFiles/python-build/lib/pdb4amber/builder
copying pdb4amber/builder/leap.py -> /home/travis/TMP/build/AmberTools/src/pdb4amber/CMakeFiles/python-build/lib/pdb4amber/builder
copying pdb4amber/builder/__init__.py -> /home/travis/TMP/build/AmberTools/src/pdb4amber/CMakeFiles/python-build/lib/pdb4amber/builder
running install
running bdist_egg
running egg_info
creating pdb4amber.egg-info
writing pdb4amber.egg-info/PKG-INFO
writing top-level names to pdb4amber.egg-info/top_level.txt
writing dependency_links to pdb4amber.egg-info/dependency_links.txt
writing entry points to pdb4amber.egg-info/entry_points.txt
writing manifest file 'pdb4amber.egg-info/SOURCES.txt'
reading manifest file 'pdb4amber.egg-info/SOURCES.txt'
writing manifest file 'pdb4amber.egg-info/SOURCES.txt'
installing library code to /home/travis/TMP/build/AmberTools/src/pdb4amber/CMakeFiles/python-build/bdist.linux-x86_64/egg
running install_lib
creating /home/travis/TMP/build/AmberTools/src/pdb4amber/CMakeFiles/python-build/bdist.linux-x86_64
creating /home/travis/TMP/build/AmberTools/src/pdb4amber/CMakeFiles/python-build/bdist.linux-x86_64/egg
creating /home/travis/TMP/build/AmberTools/src/pdb4amber/CMakeFiles/python-build/bdist.linux-x86_64/egg/pdb4amber
copying /home/travis/TMP/build/AmberTools/src/pdb4amber/CMakeFiles/python-build/lib/pdb4amber/template.py -> /home/travis/TMP/build/AmberTools/src/pdb4amber/CMakeFiles/python-build/bdist.linux-x86_64/egg/pdb4amber
copying /home/travis/TMP/build/AmberTools/src/pdb4amber/CMakeFiles/python-build/lib/pdb4amber/utils.py -> /home/travis/TMP/build/AmberTools/src/pdb4amber/CMakeFiles/python-build/bdist.linux-x86_64/egg/pdb4amber
copying /home/travis/TMP/build/AmberTools/src/pdb4amber/CMakeFiles/python-build/lib/pdb4amber/amber_builder.py -> /home/travis/TMP/build/AmberTools/src/pdb4amber/CMakeFiles/python-build/bdist.linux-x86_64/egg/pdb4amber
copying /home/travis/TMP/build/AmberTools/src/pdb4amber/CMakeFiles/python-build/lib/pdb4amber/leap_runner.py -> /home/travis/TMP/build/AmberTools/src/pdb4amber/CMakeFiles/python-build/bdist.linux-x86_64/egg/pdb4amber
copying /home/travis/TMP/build/AmberTools/src/pdb4amber/CMakeFiles/python-build/lib/pdb4amber/residue.py -> /home/travis/TMP/build/AmberTools/src/pdb4amber/CMakeFiles/python-build/bdist.linux-x86_64/egg/pdb4amber
copying /home/travis/TMP/build/AmberTools/src/pdb4amber/CMakeFiles/python-build/lib/pdb4amber/pdb4amber.py -> /home/travis/TMP/build/AmberTools/src/pdb4amber/CMakeFiles/python-build/bdist.linux-x86_64/egg/pdb4amber
copying /home/travis/TMP/build/AmberTools/src/pdb4amber/CMakeFiles/python-build/lib/pdb4amber/compat.py -> /home/travis/TMP/build/AmberTools/src/pdb4amber/CMakeFiles/python-build/bdist.linux-x86_64/egg/pdb4amber
copying /home/travis/TMP/build/AmberTools/src/pdb4amber/CMakeFiles/python-build/lib/pdb4amber/leapify.py -> /home/travis/TMP/build/AmberTools/src/pdb4amber/CMakeFiles/python-build/bdist.linux-x86_64/egg/pdb4amber
copying /home/travis/TMP/build/AmberTools/src/pdb4amber/CMakeFiles/python-build/lib/pdb4amber/visualizer.py -> /home/travis/TMP/build/AmberTools/src/pdb4amber/CMakeFiles/python-build/bdist.linux-x86_64/egg/pdb4amber
creating /home/travis/TMP/build/AmberTools/src/pdb4amber/CMakeFiles/python-build/bdist.linux-x86_64/egg/pdb4amber/builder
copying /home/travis/TMP/build/AmberTools/src/pdb4amber/CMakeFiles/python-build/lib/pdb4amber/builder/pytraj_build.py -> /home/travis/TMP/build/AmberTools/src/pdb4amber/CMakeFiles/python-build/bdist.linux-x86_64/egg/pdb4amber/builder
copying /home/travis/TMP/build/AmberTools/src/pdb4amber/CMakeFiles/python-build/lib/pdb4amber/builder/nab.py -> /home/travis/TMP/build/AmberTools/src/pdb4amber/CMakeFiles/python-build/bdist.linux-x86_64/egg/pdb4amber/builder
copying /home/travis/TMP/build/AmberTools/src/pdb4amber/CMakeFiles/python-build/lib/pdb4amber/builder/builder.py -> /home/travis/TMP/build/AmberTools/src/pdb4amber/CMakeFiles/python-build/bdist.linux-x86_64/egg/pdb4amber/builder
copying /home/travis/TMP/build/AmberTools/src/pdb4amber/CMakeFiles/python-build/lib/pdb4amber/builder/leap.py -> /home/travis/TMP/build/AmberTools/src/pdb4amber/CMakeFiles/python-build/bdist.linux-x86_64/egg/pdb4amber/builder
copying /home/travis/TMP/build/AmberTools/src/pdb4amber/CMakeFiles/python-build/lib/pdb4amber/builder/__init__.py -> /home/travis/TMP/build/AmberTools/src/pdb4amber/CMakeFiles/python-build/bdist.linux-x86_64/egg/pdb4amber/builder
copying /home/travis/TMP/build/AmberTools/src/pdb4amber/CMakeFiles/python-build/lib/pdb4amber/__init__.py -> /home/travis/TMP/build/AmberTools/src/pdb4amber/CMakeFiles/python-build/bdist.linux-x86_64/egg/pdb4amber
byte-compiling /home/travis/TMP/build/AmberTools/src/pdb4amber/CMakeFiles/python-build/bdist.linux-x86_64/egg/pdb4amber/template.py to template.pyc
byte-compiling /home/travis/TMP/build/AmberTools/src/pdb4amber/CMakeFiles/python-build/bdist.linux-x86_64/egg/pdb4amber/utils.py to utils.pyc
byte-compiling /home/travis/TMP/build/AmberTools/src/pdb4amber/CMakeFiles/python-build/bdist.linux-x86_64/egg/pdb4amber/amber_builder.py to amber_builder.pyc
byte-compiling /home/travis/TMP/build/AmberTools/src/pdb4amber/CMakeFiles/python-build/bdist.linux-x86_64/egg/pdb4amber/leap_runner.py to leap_runner.pyc
byte-compiling /home/travis/TMP/build/AmberTools/src/pdb4amber/CMakeFiles/python-build/bdist.linux-x86_64/egg/pdb4amber/residue.py to residue.pyc
byte-compiling /home/travis/TMP/build/AmberTools/src/pdb4amber/CMakeFiles/python-build/bdist.linux-x86_64/egg/pdb4amber/pdb4amber.py to pdb4amber.pyc
byte-compiling /home/travis/TMP/build/AmberTools/src/pdb4amber/CMakeFiles/python-build/bdist.linux-x86_64/egg/pdb4amber/compat.py to compat.pyc
byte-compiling /home/travis/TMP/build/AmberTools/src/pdb4amber/CMakeFiles/python-build/bdist.linux-x86_64/egg/pdb4amber/leapify.py to leapify.pyc
byte-compiling /home/travis/TMP/build/AmberTools/src/pdb4amber/CMakeFiles/python-build/bdist.linux-x86_64/egg/pdb4amber/visualizer.py to visualizer.pyc
byte-compiling /home/travis/TMP/build/AmberTools/src/pdb4amber/CMakeFiles/python-build/bdist.linux-x86_64/egg/pdb4amber/builder/pytraj_build.py to pytraj_build.pyc
byte-compiling /home/travis/TMP/build/AmberTools/src/pdb4amber/CMakeFiles/python-build/bdist.linux-x86_64/egg/pdb4amber/builder/nab.py to nab.pyc
byte-compiling /home/travis/TMP/build/AmberTools/src/pdb4amber/CMakeFiles/python-build/bdist.linux-x86_64/egg/pdb4amber/builder/builder.py to builder.pyc
byte-compiling /home/travis/TMP/build/AmberTools/src/pdb4amber/CMakeFiles/python-build/bdist.linux-x86_64/egg/pdb4amber/builder/leap.py to leap.pyc
byte-compiling /home/travis/TMP/build/AmberTools/src/pdb4amber/CMakeFiles/python-build/bdist.linux-x86_64/egg/pdb4amber/builder/__init__.py to __init__.pyc
byte-compiling /home/travis/TMP/build/AmberTools/src/pdb4amber/CMakeFiles/python-build/bdist.linux-x86_64/egg/pdb4amber/__init__.py to __init__.pyc
creating /home/travis/TMP/build/AmberTools/src/pdb4amber/CMakeFiles/python-build/bdist.linux-x86_64/egg/EGG-INFO
copying pdb4amber.egg-info/PKG-INFO -> /home/travis/TMP/build/AmberTools/src/pdb4amber/CMakeFiles/python-build/bdist.linux-x86_64/egg/EGG-INFO
copying pdb4amber.egg-info/SOURCES.txt -> /home/travis/TMP/build/AmberTools/src/pdb4amber/CMakeFiles/python-build/bdist.linux-x86_64/egg/EGG-INFO
copying pdb4amber.egg-info/dependency_links.txt -> /home/travis/TMP/build/AmberTools/src/pdb4amber/CMakeFiles/python-build/bdist.linux-x86_64/egg/EGG-INFO
copying pdb4amber.egg-info/entry_points.txt -> /home/travis/TMP/build/AmberTools/src/pdb4amber/CMakeFiles/python-build/bdist.linux-x86_64/egg/EGG-INFO
copying pdb4amber.egg-info/not-zip-safe -> /home/travis/TMP/build/AmberTools/src/pdb4amber/CMakeFiles/python-build/bdist.linux-x86_64/egg/EGG-INFO
copying pdb4amber.egg-info/top_level.txt -> /home/travis/TMP/build/AmberTools/src/pdb4amber/CMakeFiles/python-build/bdist.linux-x86_64/egg/EGG-INFO
creating dist
creating 'dist/pdb4amber-1.4-py2.7.egg' and adding '/home/travis/TMP/build/AmberTools/src/pdb4amber/CMakeFiles/python-build/bdist.linux-x86_64/egg' to it
removing '/home/travis/TMP/build/AmberTools/src/pdb4amber/CMakeFiles/python-build/bdist.linux-x86_64/egg' (and everything under it)
Processing pdb4amber-1.4-py2.7.egg
creating /home/travis/TMP/install/lib/python2.7/site-packages/pdb4amber-1.4-py2.7.egg
Extracting pdb4amber-1.4-py2.7.egg to /home/travis/TMP/install/lib/python2.7/site-packages
Adding pdb4amber 1.4 to easy-install.pth file
Installing pdb4amber script to /home/travis/TMP/install/bin
```

**Comment by hainm** [comment] 2017-09-25 05:08
I have no idea. Let me do some digging.

**Comment by hainm** [comment] 2017-09-25 05:09
May be I have not "source amber.sh" correctly.

**Comment by multiplemonomials** [comment] 2017-09-25 05:32
Oh yeah, and I found the cause of some of the test errors the other day.  The test Makefiles try to check `config.h` for `AMBER_PREFIX`, and then set `AMBERHOME=$(AMBER_PREFIX)`.  However, CMake doesn't produce a config.h, so this check fails.  The solution is to `export AMBER_PREFIX=$AMBERHOME` before running any of the test Makefiles (if your scripts use those).  Is that the cause of the NAB error perhaps?

**Comment by hainm** [comment] 2017-09-27 00:48
I bet this related to https://github.com/Amber-MD/cmake-buildscripts/commit/12f31a363d799b8db17ebb577a96a4d5a9b622e9

**Comment by multiplemonomials** [comment] 2017-09-27 00:54
Actually, hate to burst your bubble, but that issue was specific to experimental branch, and it only affected component packages, not installs.

**Comment by hainm** [comment] 2017-09-27 03:54
so I just tried on my mac:

```
from log:

Installing pdb4amber script to ../install/usr/local/bin

From reality
haichit@haimac ~/amber_git/install/usr/local/bin $ ls pmemd 
pmemd
haichit@haimac ~/amber_git/install/usr/local/bin $ ls pdb4amber
ls: pdb4amber: No such file or directory
```

Using
```
# https://cmake.org/cmake/help/v3.0/variable/CMAKE_INSTALL_PREFIX.html
make DESTDIR=../install install
# because I forgot to use -DCMAKE_INSTALL_PREFIX
```

**Comment by hainm** [comment] 2017-09-27 03:55
`parmed` script is not there too. So I guess cmake master branch won't copy python-related scripts to correct location.

**Comment by hainm** [comment] 2017-09-27 04:39
uhm, actually I don't know what's going on.

it (pdb4amber) works again on my computer.

The difference between 1st (no working) and 2nd is that

1st
```
cmake ../amber
make
make DESTDIR=../install install
```

2nd
```
cmake ../amber -DUSE_MINICONDA=False -DCMAKE_INSTALL_PREFIX=~/amber_git/install
make install
```

I don't know if I messed up anywhere else.

**Comment by hainm** [comment] 2017-09-27 04:43
Go back to 1st post.

> pkg_resources.DistributionNotFound: The 'pdb4amber==1.4' distribution was not found and is required by the application 

This is because you did not specify PYTHONPATH in `amber.sh`

```
$ cat amber.sh
# Source this script to add the variables necessary to use AMBER to your shell.

if [ -n "$BASH_SOURCE" ]; then
    this_script="$BASH_SOURCE"
elif [ -n "$DASH_SOURCE" ]; then
    this_script="$DASH_SOURCE"
elif [ -n "$ZSH_VERSION" ]; then
    setopt function_argzero
    this_script="$0"
elif eval '[[ -n ${.sh.file} ]]' 2>/dev/null; then
    eval 'this_script=${.sh.file}'
else
    echo 1>&2 "Unsupported shell. Please use bash, dash, ksh93 or zsh."
    exit 2
fi

export AMBERHOME=$(cd "$(dirname "$this_script")"; pwd)
export PATH="${AMBERHOME}/bin:${PATH}"
export DYLD_LIBRARY_PATH="$LD_LIBRARY_PATH:$AMBERHOME/lib"

# Add location of Amber Perl modules to Perl search path
if [ -z "$PERL5LIB" ]; then
	export PERL5LIB="${AMBERHOME}/lib/perl"
else
	export PERL5LIB="${AMBERHOME}/lib/perl:${PERL5LIB}"
```

```
pdb4amber -h
...pkg_resources.DistributionNotFound: The 'pdb4amber==1.4' distribution was not found and is required by the application
```

After setting
```
haichit@haimac ~/amber_git/install $ export PYTHONPATH=/Users/haichit/amber_git/install/lib/python3.6/site-packages
haichit@haimac ~/amber_git/install $ pdb4amber -h
usage: pdb4amber [-h] [-i FILE] [-o FILE] [-y] [-d] [-s STRIP_ATOM_MASK]
                 [-m MUTATION_STRING] [-p] [--constantph] [--most-populous]
                 [--keep-altlocs] [--reduce] [--no-reduce-db] [--pdbid]
                 [--add-missing-atoms] [--model MODEL] [-l FILE] [-v]
                 [--leap-template] [--no-conect] [--noter]
                 [input]
```

**Comment by multiplemonomials** [comment] 2017-09-27 06:05
OOOHHH, _I_ know what happened!

In `CreatePathScript.cmake`, I had this line:
```cmake
	if(${BUILD_PYTHON} AND ("${PYTHON_INSTALL}" STREQUAL LOCAL))
 < add PYTHONPATH segment to amber.sh>
```
And then we deleted the `PYTHON_INSTALL` variable.

It still worked for me because all of my build directories still had the `PYTHON_INSTALL` variable from when it used to exist.  That's why I couldn't reproduce it.

**Comment by multiplemonomials** [comment] 2017-09-27 06:06
Oh, and by the way, just double checking.  You know that you can run cmake in an already-configured build directory to reconfigure it without having to recompile anything, right?

**Comment by hainm** [comment] 2017-09-27 12:57
No I don't know that.

I had to use 
```
make DESTDIR=../install install
```

**Comment by hainm** [comment] 2017-09-27 13:17
> It still worked for me because all of my build directories still had the PYTHON_INSTALL variable from when it used to exist. That's why I couldn't reproduce it.

yeah, that's why I always try to test on travis or circleci, very fresh.

**Comment by multiplemonomials** [comment] 2017-10-02 22:09
Should be fixed as of merge of experimental to master

**Closed by multiplemonomials** 2017-10-02 22:09 UTC
Labels: build error
