### ISSUE TITLE
rism_report_c.F90:(.text+0x29): undefined reference to `_gfortran_stop_numeric_f08'

### ISSUE THREAD

**Issue by hainm** [Amber-MD/cmake-buildscripts#62] opened 2017-10-02 05:11 UTC
Not sure if this is due to the common issue of linking to miniconda/lib or not. But just post here just in case (and for future reference).

```
                               1
Warning: Unused variable 'nx' declared at (1)
[ 30%] Linking Fortran shared library libsff.so
../rism/librism.a(rism_report_c.F90.o): In function `__rism_report_c_MOD_halt':
rism_report_c.F90:(.text+0x29): undefined reference to `_gfortran_stop_numeric_f08'
../rism/librism.a(rism_report_c.F90.o): In function `__rism_report_c_MOD_error_rsrsrsr':
rism_report_c.F90:(.text+0x2dd): undefined reference to `_gfortran_stop_numeric_f08'
../rism/librism.a(rism_report_c.F90.o): In function `__rism_report_c_MOD_error_rsrsr':
rism_report_c.F90:(.text+0x403): undefined reference to `_gfortran_stop_numeric_f08'
collect2: error: ld returned 1 exit status
make[2]: *** [AmberTools/src/sff/libsff.so] Error 1
make[1]: *** [AmberTools/src/sff/CMakeFiles/sff.dir/all] Error 2
make: *** [all] Error 2
```

https://travis-ci.org/Amber-MD/ambertools-ci/jobs/282096144
[travis_log.txt](https://github.com/Amber-MD/cmake-buildscripts/files/1347956/travis_log.txt)

**Comment by multiplemonomials** [comment] 2017-10-02 05:14
Yeah this is probably the miniconda thing.  It looks like this error is a symptom of a ligbfortran version mismatch.

**Comment by multiplemonomials** [comment] 2017-10-02 05:16
Also, I'm about to merge CMake into master.  I ran through the makefile build system, and after fixing a change that broke `byacc`, everything works fine.  Test suite output (from the Makefile-built Amber):
```
2088 file comparisons passed
25 file comparisons failed
0 tests experienced errors
```

**Comment by hainm** [comment] 2017-10-02 05:23
> 25 file comparisons failed

what are they? can you post the output here?

is that Linux or MacOS?

**Comment by multiplemonomials** [comment] 2017-10-02 05:24
Actually, I just realized that my proposed fix for the miniconda problem might not affect implicit compiler libraries like `libgfortran`.  Is there any way you could pass the `VERBOSE=1` argument to `make` on the next Travis run?  Then I could see the link command and get a better idea of what's going on.

**Comment by multiplemonomials** [comment] 2017-10-02 05:25
I'm on Windows Subsystem for Linux, so Linux I guess.  I figured they were just roundoff errors.

**Comment by hainm** [comment] 2017-10-02 05:25
make install VERBOSE=1?

**Comment by hainm** [comment] 2017-10-02 05:27
> I figured they were just roundoff errors.

I would like to have a look please.

**Comment by hainm** [comment] 2017-10-02 05:27
all the outputs are in $AMBERHOME/log(s)

**Comment by multiplemonomials** [comment] 2017-10-02 05:28
Here you go.  Looks like it's emil and FEW. 
```
#########################################################################
                             PERFORMING FEW TESTS

If all of the tests below fail then check the system specific path to
the locally installed Perl libraries.
For details on test issues and on how to fix them read:
/mnt/j/amber-cmake/amber/AmberTools/src/FEW/examples/test/few.log

CLEANING
PERFORMING TEST 01: Step1 of RESP charge calculation
CHECKING IN TEST 01: Step1 of RESP charge calculation
possible FAILURE:  file /mnt/j/amber-cmake/amber/AmberTools/src/FEW/examples/test/gauss/L51a/L51a.gcrt does not exist.
==============================================================
mv: cannot stat '/mnt/j/amber-cmake/amber/AmberTools/src/FEW/examples/test/gauss': No such file or directory
PERFORMING TEST 02: Step2 of RESP charge calculation and setup of MD simulations
CHECKING IN TEST 02: Step2 of RESP charge calculation and setup of MD simulations
possible FAILURE:  file /mnt/j/amber-cmake/amber/AmberTools/src/FEW/examples/test/gauss/L51a/L51a.gout.xyz does not exist.
==============================================================
possible FAILURE:  file /mnt/j/amber-cmake/amber/AmberTools/src/FEW/examples/test/leap/L51a/L51a_resp.lib does not exist.
==============================================================
possible FAILURE:  file /mnt/j/amber-cmake/amber/AmberTools/src/FEW/examples/test/leap/L51a/L51a.frcmod does not exist.
==============================================================
possible FAILURE:  file /mnt/j/amber-cmake/amber/AmberTools/src/FEW/examples/test/leap/L51a/L51a_com.pdb does not exist.
==============================================================
possible FAILURE:  file /mnt/j/amber-cmake/amber/AmberTools/src/FEW/examples/test/leap/L51a/L51a_rec.pdb does not exist.
==============================================================
possible FAILURE:  file /mnt/j/amber-cmake/amber/AmberTools/src/FEW/examples/test/leap/L51a/L51a_lig.pdb does not exist.
==============================================================
possible FAILURE:  file /mnt/j/amber-cmake/amber/AmberTools/src/FEW/examples/test/MD_resp/L51a/cryst/L51a_solv_com.crd does not exist.
==============================================================
possible FAILURE:  file /mnt/j/amber-cmake/amber/AmberTools/src/FEW/examples/test/MD_resp/L51a/cryst/L51a_solv_rec.crd does not exist.
==============================================================
possible FAILURE:  file /mnt/j/amber-cmake/amber/AmberTools/src/FEW/examples/test/MD_resp/L51a/cryst/L51a_solv_lig.crd does not exist.
==============================================================
possible FAILURE:  file /mnt/j/amber-cmake/amber/AmberTools/src/FEW/examples/test/MD_resp/L51a/lig/equi/md_nvt_red_06.in does not exist.
==============================================================
possible FAILURE:  file /mnt/j/amber-cmake/amber/AmberTools/src/FEW/examples/test/MD_resp/rec/equi/md_nvt_red_06.in does not exist.
==============================================================
possible FAILURE:  file /mnt/j/amber-cmake/amber/AmberTools/src/FEW/examples/test/MD_resp/L51a/lig/prod/md_prod_001.in does not exist.
==============================================================
possible FAILURE:  file /mnt/j/amber-cmake/amber/AmberTools/src/FEW/examples/test/MD_resp/rec/prod/md_prod_001.in does not exist.
==============================================================
/mnt/j/amber-cmake/amber/AmberTools/src/FEW/examples/test/MD_resp/L51a/com/prod: No such file or directory.
Makefile:246: recipe for target 'test.FEW' failed
make[1]: *** [test.FEW] Error 1
```
```
export TESTsander='/home/jamie/amber-cmake/amber/bin/sander'; unset DO_PARALLEL; cd emil/emil_sander_gbsa && ./Run.emil TRUE
DO_PARALLEL not set... testing emil in serial.
diffing mdout.emil.0.0.save with mdout.emil.0.0
PASSED
==============================================================
diffing emil.log.0.0.save with emil.log.0.0
possible FAILURE:  check emil.log.0.0.dif
==============================================================
diffing mdout.emil.0.1.save with mdout.emil.0.1
possible FAILURE:  check mdout.emil.0.1.dif
==============================================================
diffing emil.log.0.1.save with emil.log.0.1
possible FAILURE:  check emil.log.0.1.dif
==============================================================
diffing mdout.emil.0.9.save with mdout.emil.0.9
possible FAILURE:  check mdout.emil.0.9.dif
==============================================================
diffing emil.log.0.9.save with emil.log.0.9
possible FAILURE:  check emil.log.0.9.dif
==============================================================
export TESTsander='/home/jamie/amber-cmake/amber/bin/sander'; unset DO_PARALLEL; cd emil/emil_sander_tip3p && ./Run.emil TRUE
DO_PARALLEL not set... testing emil in serial.
diffing mdout.emil.0.1.save with mdout.emil.0.1
possible FAILURE:  check mdout.emil.0.1.dif
==============================================================
diffing emil.log.0.1.save with emil.log.0.1
possible FAILURE:  check emil.log.0.1.dif
==============================================================
diffing mdout.emil.0.5.save with mdout.emil.0.5
possible FAILURE:  check mdout.emil.0.5.dif
==============================================================
diffing emil.log.0.5.save with emil.log.0.5
possible FAILURE:  check emil.log.0.5.dif
==============================================================
diffing mdout.emil.0.9.save with mdout.emil.0.9
possible FAILURE:  check mdout.emil.0.9.dif
==============================================================
diffing emil.log.0.9.save with emil.log.0.9
possible FAILURE:  check emil.log.0.9.dif
==============================================================
```

**Comment by multiplemonomials** [comment] 2017-10-02 05:28
Also the logs got deleted because I ran git clean.  I got these from my terminal history.

**Comment by hainm** [comment] 2017-10-02 05:30
sounds good.

**Comment by hainm** [comment] 2017-10-02 05:32
btw, here is the cmake build script on travis:

https://github.com/Amber-MD/ambertools-ci-base/blob/master/devtools/ci/load_functions.sh#L79

feel free to make a PR. After making change there, I will trigger the travis build:
https://travis-ci.org/Amber-MD/ambertools-ci/builds/282107799

**Comment by hainm** [comment] 2017-10-02 05:35
just added you to 2 above repos. Feel free to play with your cmake.

**Comment by multiplemonomials** [comment] 2017-10-02 05:42
Cool, thanks.  I'll look at it later this week, it it turns out that my other change doesn't fix it.  I'm kind of busy with an essay right now.

**Comment by multiplemonomials** [comment] 2017-10-13 06:06
Looks like this issue is fixed by the workaround and is thus a duplicate of #67, so I'm closing it for now. 

I saw the Travis build failure on Mac, and am creating a new issue for it.

**Closed by multiplemonomials** 2017-10-13 06:06 UTC
