### ISSUE TITLE
Error: Symbol ‘atompositions_fce’ at (1) has no IMPLICIT type

### ISSUE THREAD

**Issue by hainm** [Amber-MD/cmake-buildscripts#55] opened 2017-09-26 00:20 UTC
I swear that I am not able compile cmake stuff successfully on my Mac and casegroup recently.
Only travis is working and you know it's painful to debug.

btw, please check below message and also check attached file (need to rename it to `report.tar`)

```
Error: Symbol ‘atompositions_fce’ at (1) has no IMPLICIT type
/Users/haichit/amber_git/amber/AmberTools/src/rism/amber_rism_interface.F90:1234:26:

          atomPositions_fce => safemem_realloc(atomPositions_fce, 3, rism_3d%solute%numAtoms)
                          1
Error: Symbol ‘atompositions_fce’ at (1) has no IMPLICIT type
make[2]: *** [AmberTools/src/rism/CMakeFiles/sander_rism_interface.dir/amber_rism_interface.F90.o] Error 1
make[1]: *** [AmberTools/src/rism/CMakeFiles/sander_rism_interface.dir/all] Error 2
make: *** [all] Error 2
```

[report.txt](https://github.com/Amber-MD/cmake-buildscripts/files/1331319/report.txt)

**Comment by multiplemonomials** [comment] 2017-09-27 00:35
Did you change anything that made this start occurring?

**Comment by hainm** [comment] 2017-09-27 00:36
Nope.

(non-cmake is still ok).

**Comment by multiplemonomials** [comment] 2017-09-27 00:47
And what machine exactly does this happen on?

**Comment by hainm** [comment] 2017-09-27 00:50
My mac.

I think i attached everything you need.

**Comment by multiplemonomials** [comment] 2017-09-27 00:52
This _might_ have been fixed in the current experimental branch.  I certainly can't reproduce it, and the CMake stuff had some major changes.  I'm going to merge it into master in a few days so we'll see if it's fixed then.

**Comment by hainm** [comment] 2017-09-27 04:20
> I'm going to merge it into master in a few days so we'll see if it's fixed then.

ok thanks. But please be more careful this time. If you are getting trouble or not clear about anything (e.g: if a module should exist or not), just let me know. 

Ideally, here is the workflow
```
git checkout -b try_merge_master origin/master
git checkout try_merge_master
# then merge your cmake branch, fix merge conflict, do testing
# Post any test failures here (current master branch only fails with FEW test) so we can have a look.

# if everything is ok
git checkout master
git merge try_merge_master
```

**Comment by multiplemonomials** [comment] 2017-09-27 06:01
Alright, that is a safer way.

**Comment by hainm** [comment] 2017-09-27 13:04
or better, after successfully merge to "try_merge_master", make a tarfile and update here so I can setup the testing on travis for you.

**Comment by hainm** [comment] 2017-09-28 23:36
uhm, I look the travis build in more details and turns out rism build also failed there.
```
                               1
Warning: Unused variable 'nx' declared at (1)
[ 30%] Linking Fortran shared library libsff.so
../rism/librism.a(rism_report_c.F90.o): In function `__rism_report_c_MOD_halt':
rism_report_c.F90:(.text+0x29): undefined reference to `_gfortran_stop_numeric_f08'
../rism/librism.a(rism_report_c.F90.o): In function `__rism_report_c_MOD_error_rsrsrsr':
rism_report_c.F90:(.text+0x2dd): undefined reference to `_gfortran_stop_numeric_f08'
../rism/librism.a(rism_report_c.F90.o): In function `__rism_report_c_MOD_error_rsrsr':
rism_report_c.F90:(.text+0x403): undefined reference to `_gfortran_stop_numeric_f08'
collect2: error: ld returned 1 exit status
make[2]: *** [AmberTools/src/sff/libsff.so] Error 1
make[1]: *** [AmberTools/src/sff/CMakeFiles/sff.dir/all] Error 2
make: *** [all] Error 2
```

https://travis-ci.org/Amber-MD/ambertools-ci/jobs/280731479

**Comment by multiplemonomials** [comment] 2017-09-28 23:42
I'm willing to bet that this is the Miniconda search path issue again.  That's really the common denominator between your builds and mine.  For now, I suggest trying without conda in your path and seeing if it builds successfully.

**Comment by hainm** [comment] 2017-09-28 23:43
ok will do.

**Comment by hainm** [comment] 2017-09-28 23:46
ha, chicken and egg issue. If not using `conda`, I would have hard time to install cmake 3.9. :D

**Comment by hainm** [comment] 2017-09-28 23:48
... on travis.

**Comment by multiplemonomials** [comment] 2017-10-02 04:48
OK, I finally was able to reproduce this!  This error is caused by running a build with the makefile build system, then running a build with CMake without `git clean`-ing the Amber source tree.  This is always going to cause problems because module files from the Makefile system will end up on the module path for the CMake build system.

So just run `git clean -dxf` in the source tree, and you should be good!  Yes I know it's annoying, but at least there's a fix.

**Comment by multiplemonomials** [comment] 2017-10-02 04:48
whoops wrong button

**Comment by hainm** [comment] 2017-10-02 04:56
how we deal that without git, e.g:  release version. I guess we have to make sure "make clean" would do the job.

**Comment by multiplemonomials** [comment] 2017-10-02 05:03
yeah

**Comment by multiplemonomials** [comment] 2017-10-06 05:13
I just checked, and `make clean` gets rid of all the module files, and should prevent this bug from happening.  We just have to make sure to put that in the manual...

**Closed by multiplemonomials** 2017-10-06 05:13 UTC
Labels: build error
