### ISSUE TITLE
cpptraj: symbol lookup error: /home/travis/miniconda/lib/libreadline.so.6: undefined symbol: 

### ISSUE THREAD

**Issue by hainm** [Amber-MD/cmake-buildscripts#33] opened 2017-09-15 02:44 UTC
I am not sure it's due to the Miniconda version I am using or because of other reasons. Just bring this to your attention.

Please see the log here: https://travis-ci.org/Amber-MD/ambertools-ci/builds/275717534

cheers

**Comment by hainm** [comment] 2017-09-15 02:45
or may be libreadline from Miniconda was built with older compiler.

**Comment by multiplemonomials** [comment] 2017-09-15 02:51
I haven't dug deep into it yet, but I suspect that something is adding Miniconda to `LD_LIBRARY_PATH`, hence all of the CMake warnings about not being able to generate a safe search path.  Miniconda shouldn't be in `LD_LIBRARY_PATH` for CMake

**Comment by hainm** [comment] 2017-09-15 02:57
I don't think I ever used `LD_LIBRARY_PATH` from Miniconda (got many trouble before).

**Comment by hainm** [comment] 2017-09-15 03:12
I got the same error on circleci (via ssh)

Here is the LD_LIBRARY_PATH (after source $HOME/TMP/install/amber.sh)
```bash
$ echo  $LD_LIBRARY_PATH 
:/home/ubuntu/TMP/install/lib
```

```
/home/ubuntu/TMP/install/bin/cpptraj: symbol lookup error: /home/ubuntu/miniconda/lib/libreadline.so.6: undefined symbol: PC
/home/ubuntu/TMP/install/bin/cpptraj: Program error
```

**Comment by multiplemonomials** [comment] 2017-09-15 04:03
Hmm I'm really not sure what's going on here.  Somehow `miniconda/lib` is getting added to the linker search path, since CMake is complaining about it:
```
CMake Warning at AmberTools/src/cpptraj/src/CMakeLists.txt:106 (add_executable):
  Cannot generate a safe runtime search path for target cpptraj because files
  in some directories may conflict with libraries in implicit directories:

    runtime library [libbz2.so.1.0] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /home/travis/miniconda/lib
    runtime library [libz.so.1] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /home/travis/miniconda/lib
    runtime library [libreadline.so.6] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /home/travis/miniconda/lib
```
You can see if it goes away when you provide the CMake option `-DFORCE_INTERNAL_LIBS=readline`.  You can also disable it entirely by supplying `-DFORCE_DISABLE_LIBS=readline`.

**Comment by hainm** [comment] 2017-09-15 05:03
> -DFORCE_INTERNAL_LIBS=readline. 

yeah this helps.

**Comment by multiplemonomials** [comment] 2017-09-15 05:09
Oh by the way you can also pass the options `-DUNUSED_WARNINGS=FALSE -DUNINITIALIZED_WARNINGS=FALSE` to turn off all of those annoying warnings.   This will soon eb the default.

**Comment by multiplemonomials** [comment] 2017-09-15 21:14
Now that we have a workaround I think we can close this.  Let me know if you're able to reproduce this  in a more easily debuggable environment.

**Closed by multiplemonomials** 2017-09-15 21:14 UTC
