### ISSUE TITLE
pytraj failure: Library not loaded: @rpath/libcpptraj.dylib

### ISSUE THREAD

**Issue by hainm** [Amber-MD/cmake-buildscripts#97] opened 2017-11-19 04:55 UTC
```
AmberTools/test/pytraj $ make
Testing serial pytraj
python test.py
Traceback (most recent call last):
  File "test.py", line 2, in <module>
    import pytraj as pt
  File "/Users/haichit/amber_git/cmake/py35/lib/python3.5/site-packages/pytraj-2.0.3.dev0-py3.5-macosx-10.6-x86_64.egg/pytraj/__init__.py", line 24, in <module>
    from .utils.misc import info
  File "/Users/haichit/amber_git/cmake/py35/lib/python3.5/site-packages/pytraj-2.0.3.dev0-py3.5-macosx-10.6-x86_64.egg/pytraj/utils/misc.py", line 7, in <module>
    from pytraj.core.c_options import set_world_silent
  File "/Users/haichit/amber_git/cmake/py35/lib/python3.5/site-packages/pytraj-2.0.3.dev0-py3.5-macosx-10.6-x86_64.egg/pytraj/core/__init__.py", line 2, in <module>
    from .topology_objects import Atom, Residue, Molecule
  File "/Users/haichit/amber_git/cmake/py35/lib/python3.5/site-packages/pytraj-2.0.3.dev0-py3.5-macosx-10.6-x86_64.egg/pytraj/core/topology_objects.py", line 7, in <module>
    __bootstrap__()
  File "/Users/haichit/amber_git/cmake/py35/lib/python3.5/site-packages/pytraj-2.0.3.dev0-py3.5-macosx-10.6-x86_64.egg/pytraj/core/topology_objects.py", line 6, in __bootstrap__
    imp.load_dynamic(__name__,__file__)
  File "/Users/haichit/miniconda3/lib/python3.6/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: dlopen(/Users/haichit/amber_git/cmake/py35/lib/python3.5/site-packages/pytraj-2.0.3.dev0-py3.5-macosx-10.6-x86_64.egg/pytraj/core/topology_objects.cpython-35m-darwin.so, 2): Library not loaded: @rpath/libcpptraj.dylib
  Referenced from: /Users/haichit/amber_git/cmake/py35/lib/python3.5/site-packages/pytraj-2.0.3.dev0-py3.5-macosx-10.6-x86_64.egg/pytraj/core/topology_objects.cpython-35m-darwin.so
  Reason: image not found
test.pytraj:  Program error
```

**Comment by hainm** [comment] 2017-11-19 04:56
kind of weird since I am able to import and run simple test in command line
```
$ python -c "import pytraj; print(pytraj); pytraj.run_tests()"
<module 'pytraj' from '/Users/haichit/amber_git/cmake/py35/lib/python3.5/site-packages/pytraj-2.0.3.dev0-py3.5-macosx-10.6-x86_64.egg/pytraj/__init__.py'>
try to load sample data
try to make all action objects
try to make all analysis objects
try to make all dataset stuff
try to make structure-related objects
try to create Trajectory-like objects
other stuff. throw all tests don't belong anywhere else here
OK
```

**Comment by hainm** [comment] 2017-11-19 04:57
Interestingly if I `unset DYLD_LIBRARY_PATH` in my terminal, I am able to reproduce error in my 1st post.

**Comment by multiplemonomials** [comment] 2017-11-19 07:00
Yeah, I think the test scripts do something that affects that variable.  This is a duplicate of #70 though.

**Closed by multiplemonomials** 2017-11-19 07:00 UTC
